import Wrapper from "@/components/wrapper/Wrapper";
import Provider from "../components/Provider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <nav>Nav</nav>
          <main className="container">
            <Wrapper>{children}</Wrapper>
          </main>
        </Provider>
      </body>
    </html>
  );
}
